# Generated by Django 5.2.5 on 2025-09-28 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QrCode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lien',
            name='qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QrCode.qrcode'),
        ),
        migrations.AddField(
            model_name='email',
            name='qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='QrCode.qrcode'),
        ),
        migrations.AddField(
            model_name='contact',
            name='qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='QrCode.qrcode'),
        ),
        migrations.AddField(
            model_name='sms',
            name='qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='QrCode.qrcode'),
        ),
        migrations.AddField(
            model_name='texte',
            name='qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='texte', to='QrCode.qrcode'),
        ),
        migrations.AddField(
            model_name='wifi',
            name='qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wifi', to='QrCode.qrcode'),
        ),
    ]
